services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    depends_on:
      - api
    environment:
      WATCHPACK_POLLING: "true"
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules

volumes:
  postgres_data:
