/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Cart: () => import('#controllers/cart_controller'),
  ExchangeRates: () => import('#controllers/exchange_rates_controller'),
  NewPassword: () => import('#controllers/new_password_controller'),
  Orders: () => import('#controllers/orders_controller'),
  PasswordResetLink: () => import('#controllers/password_reset_link_controller'),
  ProductImages: () => import('#controllers/product_images_controller'),
  Products: () => import('#controllers/products_controller'),
  RegisteredUser: () => import('#controllers/registered_user_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  Sellers: () => import('#controllers/sellers_controller'),
  ShippingProfiles: () => import('#controllers/shipping_profiles_controller'),
  StaffDisputes: () => import('#controllers/staff_disputes_controller'),
  StaffOverview: () => import('#controllers/staff_overview_controller'),
  StorefrontOrders: () => import('#controllers/storefront_orders_controller'),
  StorefrontProducts: () => import('#controllers/storefront_products_controller'),
  StorefrontShops: () => import('#controllers/storefront_shops_controller'),
  StripeConnect: () => import('#controllers/stripe_connect_controller'),
  StripeWebhook: () => import('#controllers/stripe_webhook_controller'),
  Translations: () => import('#controllers/translations_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
