/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  NewPassword: () => import('#controllers/new_password_controller'),
  PasswordResetLink: () => import('#controllers/password_reset_link_controller'),
  RegisteredUser: () => import('#controllers/registered_user_controller'),
  Sellers: () => import('#controllers/sellers_controller'),
  Translations: () => import('#controllers/translations_controller'),
}
