/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type DisputeTransformer from '#transformers/dispute_transformer'
import type OrderItemTransformer from '#transformers/order_item_transformer'
import type OrderTransformer from '#transformers/order_transformer'
import type PaymentTransformer from '#transformers/payment_transformer'
import type ProductImageTransformer from '#transformers/product_image_transformer'
import type ProductOptionTransformer from '#transformers/product_option_transformer'
import type ProductOptionValueTransformer from '#transformers/product_option_value_transformer'
import type ProductTransformer from '#transformers/product_transformer'
import type ProductVariantTransformer from '#transformers/product_variant_transformer'
import type PublicOrderTransformer from '#transformers/public_order_transformer'
import type PublicProductCardTransformer from '#transformers/public_product_card_transformer'
import type PublicProductTransformer from '#transformers/public_product_transformer'
import type PublicProductVariantTransformer from '#transformers/public_product_variant_transformer'
import type PublicShopTransformer from '#transformers/public_shop_transformer'
import type ReviewTransformer from '#transformers/review_transformer'
import type SellerTransformer from '#transformers/seller_transformer'
import type ShippingProfileTransformer from '#transformers/shipping_profile_transformer'
import type ShippingRateTransformer from '#transformers/shipping_rate_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Dispute = InferData<DisputeTransformer>
  export namespace Dispute {
    export type Variants = InferVariants<DisputeTransformer>
  }
  export type OrderItem = InferData<OrderItemTransformer>
  export namespace OrderItem {
    export type Variants = InferVariants<OrderItemTransformer>
  }
  export type Order = InferData<OrderTransformer>
  export namespace Order {
    export type Variants = InferVariants<OrderTransformer>
  }
  export type Payment = InferData<PaymentTransformer>
  export namespace Payment {
    export type Variants = InferVariants<PaymentTransformer>
  }
  export type ProductImage = InferData<ProductImageTransformer>
  export namespace ProductImage {
    export type Variants = InferVariants<ProductImageTransformer>
  }
  export type ProductOption = InferData<ProductOptionTransformer>
  export namespace ProductOption {
    export type Variants = InferVariants<ProductOptionTransformer>
  }
  export type ProductOptionValue = InferData<ProductOptionValueTransformer>
  export namespace ProductOptionValue {
    export type Variants = InferVariants<ProductOptionValueTransformer>
  }
  export type Product = InferData<ProductTransformer>
  export namespace Product {
    export type Variants = InferVariants<ProductTransformer>
  }
  export type ProductVariant = InferData<ProductVariantTransformer>
  export namespace ProductVariant {
    export type Variants = InferVariants<ProductVariantTransformer>
  }
  export type PublicOrder = InferData<PublicOrderTransformer>
  export namespace PublicOrder {
    export type Variants = InferVariants<PublicOrderTransformer>
  }
  export type PublicProductCard = InferData<PublicProductCardTransformer>
  export namespace PublicProductCard {
    export type Variants = InferVariants<PublicProductCardTransformer>
  }
  export type PublicProduct = InferData<PublicProductTransformer>
  export namespace PublicProduct {
    export type Variants = InferVariants<PublicProductTransformer>
  }
  export type PublicProductVariant = InferData<PublicProductVariantTransformer>
  export namespace PublicProductVariant {
    export type Variants = InferVariants<PublicProductVariantTransformer>
  }
  export type PublicShop = InferData<PublicShopTransformer>
  export namespace PublicShop {
    export type Variants = InferVariants<PublicShopTransformer>
  }
  export type Review = InferData<ReviewTransformer>
  export namespace Review {
    export type Variants = InferVariants<ReviewTransformer>
  }
  export type Seller = InferData<SellerTransformer>
  export namespace Seller {
    export type Variants = InferVariants<SellerTransformer>
  }
  export type ShippingProfile = InferData<ShippingProfileTransformer>
  export namespace ShippingProfile {
    export type Variants = InferVariants<ShippingProfileTransformer>
  }
  export type ShippingRate = InferData<ShippingRateTransformer>
  export namespace ShippingRate {
    export type Variants = InferVariants<ShippingRateTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
