/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'token'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
}

export class ProductOptionValueSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'position', 'productOptionId', 'updatedAt', 'value'] as const
  $columns = ProductOptionValueSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number
  @column()
  declare productOptionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}

export class ProductOptionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'position', 'productId', 'updatedAt'] as const
  $columns = ProductOptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare productId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductVariantOptionValueSchema extends BaseModel {
  static $columns = ['id', 'productOptionValueId', 'productVariantId'] as const
  $columns = ProductVariantOptionValueSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productOptionValueId: number
  @column()
  declare productVariantId: number
}

export class ProductVariantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'price', 'productId', 'sku', 'stockQuantity', 'updatedAt'] as const
  $columns = ProductVariantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare price: string
  @column()
  declare productId: number
  @column()
  declare sku: string | null
  @column()
  declare stockQuantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'sellerId', 'slug', 'status', 'title', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sellerId: number
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SellerSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'payoutStatus', 'shopName', 'slug', 'status', 'updatedAt', 'userId'] as const
  $columns = SellerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payoutStatus: string
  @column()
  declare shopName: string
  @column()
  declare slug: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
