/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DisputeSchema extends BaseModel {
  static $columns = ['createdAt', 'detail', 'id', 'openedByUserId', 'orderId', 'reason', 'resolutionNote', 'resolvedAt', 'resolvedByUserId', 'status', 'updatedAt'] as const
  $columns = DisputeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detail: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare openedByUserId: string
  @column()
  declare orderId: string
  @column()
  declare reason: string
  @column()
  declare resolutionNote: string | null
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedByUserId: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['createdAt', 'currency', 'id', 'imagePath', 'orderId', 'productSlug', 'productTitle', 'productVariantId', 'quantity', 'unitPriceCents', 'updatedAt', 'variantLabel'] as const
  $columns = OrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imagePath: string | null
  @column()
  declare orderId: string
  @column()
  declare productSlug: string
  @column()
  declare productTitle: string
  @column()
  declare productVariantId: string | null
  @column()
  declare quantity: number
  @column()
  declare unitPriceCents: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare variantLabel: string
}

export class OrderSchema extends BaseModel {
  static $columns = ['acceptedAt', 'cancelReason', 'cancelledAt', 'completedAt', 'contactEmail', 'createdAt', 'currency', 'expiresAt', 'id', 'paymentId', 'payoutReleaseAt', 'platformFeeCents', 'reference', 'refundedCents', 'sellerId', 'sellerOrderNumber', 'shippedAt', 'shippingCents', 'shippingCity', 'shippingCountry', 'shippingLine1', 'shippingLine2', 'shippingName', 'shippingPostalCode', 'status', 'stripeRefundId', 'stripeTransferId', 'stripeTransferReversalId', 'subtotalCents', 'trackingNumber', 'updatedAt', 'userId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare cancelReason: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare contactEmail: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare paymentId: string | null
  @column.dateTime()
  declare payoutReleaseAt: DateTime | null
  @column()
  declare platformFeeCents: bigint | number
  @column()
  declare reference: string
  @column()
  declare refundedCents: bigint | number
  @column()
  declare sellerId: string
  @column()
  declare sellerOrderNumber: number
  @column.dateTime()
  declare shippedAt: DateTime | null
  @column()
  declare shippingCents: bigint | number
  @column()
  declare shippingCity: string
  @column()
  declare shippingCountry: string
  @column()
  declare shippingLine1: string
  @column()
  declare shippingLine2: string | null
  @column()
  declare shippingName: string
  @column()
  declare shippingPostalCode: string
  @column()
  declare status: string
  @column()
  declare stripeRefundId: string | null
  @column()
  declare stripeTransferId: string | null
  @column()
  declare stripeTransferReversalId: string | null
  @column()
  declare subtotalCents: bigint | number
  @column()
  declare trackingNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'token'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare token: string
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amountCents', 'createdAt', 'currency', 'id', 'lastError', 'status', 'stripePaymentIntentId', 'updatedAt', 'userId'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amountCents: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastError: string | null
  @column()
  declare status: string
  @column()
  declare stripePaymentIntentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class ProductImageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'path', 'position', 'productId', 'updatedAt'] as const
  $columns = ProductImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare path: string
  @column()
  declare position: number
  @column()
  declare productId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductOptionValueSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'position', 'productOptionId', 'updatedAt', 'value'] as const
  $columns = ProductOptionValueSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare position: number
  @column()
  declare productOptionId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}

export class ProductOptionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'position', 'productId', 'updatedAt'] as const
  $columns = ProductOptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare productId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductVariantOptionValueSchema extends BaseModel {
  static $columns = ['id', 'productOptionValueId', 'productVariantId'] as const
  $columns = ProductVariantOptionValueSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productOptionValueId: string
  @column()
  declare productVariantId: string
}

export class ProductVariantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'priceCents', 'productId', 'sku', 'stockQuantity', 'updatedAt'] as const
  $columns = ProductVariantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare priceCents: bigint | number
  @column()
  declare productId: string
  @column()
  declare sku: string | null
  @column()
  declare stockQuantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductSchema extends BaseModel {
  static $columns = ['createdAt', 'currency', 'description', 'id', 'sellerId', 'shippingProfileId', 'slug', 'status', 'title', 'tracksInventory', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare sellerId: string
  @column()
  declare shippingProfileId: string | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare tracksInventory: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SellerSchema extends BaseModel {
  static $columns = ['country', 'createdAt', 'currency', 'description', 'id', 'nextOrderNumber', 'payoutStatus', 'shopName', 'slug', 'status', 'stripeAccountId', 'updatedAt', 'userId'] as const
  $columns = SellerSchema.$columns
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nextOrderNumber: number
  @column()
  declare payoutStatus: string
  @column()
  declare shopName: string
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare stripeAccountId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class ShippingProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'sellerId', 'updatedAt'] as const
  $columns = ShippingProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare sellerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ShippingRateSchema extends BaseModel {
  static $columns = ['additionalItemCents', 'createdAt', 'destination', 'firstItemCents', 'id', 'shippingProfileId', 'updatedAt'] as const
  $columns = ShippingRateSchema.$columns
  @column()
  declare additionalItemCents: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare destination: string
  @column()
  declare firstItemCents: bigint | number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare shippingProfileId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class StripeEventSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'type', 'updatedAt'] as const
  $columns = StripeEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'locale', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare locale: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
